name: "ISpy Agent dvr"
version: 0.1
slug: ispy_agent_dvr
description: "iSpy is the world’s most popular open source video surveillance application. It's compatible with the the vast majority of consumer webcams and IP cameras."
arch:
  - amd64
map:
  - share:rw
url: "https://www.ispyconnect.com/"
ingress: true
ingress_port: 8090
ports:
  8090/tcp: 8090
  3478/udp: 3478
  50000/udp: 50000
  50001/udp: 50001
  50002/udp: 50002
  50003/udp: 50003
  50004/udp: 50004
  50005/udp: 50005
  50006/udp: 50006
  50007/udp: 50007
  50008/udp: 50008
  50009/udp: 50009
  50010/udp: 50010
