name: "Firefly III"
version: 0.15
slug: firefly_iii
description: "Nog geen beschrijving"
arch:
  - amd64
webui: http://[HOST]:[PORT:8080]
ports:
  8080/tcp: 9080
ports_description:
  80/tcp: Web interface
map:
  - share:rw
options:
  APP_KEY: CHANGEME_32_CHARS
  DEFAULT_LANGUAGE: nl_NL
schema:
  APP_KEY: str
  DEFAULT_LANGUAGE: match([a-z][a-z]_[A-Z][A-Z])
services:
  - mysql:need
hassio_api: true
